### ISSUE TITLE
Maintainer required?

### ISSUE THREAD

**Issue by flexoid** [brandedcrate/errbit_pivotal_plugin#3]
Hello.

We just recently updated Errbit to the latest version, with removed PivotalTracker integration (actually, we [noticed that earlier](https://github.com/errbit/errbit/issues/899)).

I can test this version of plugin to work with latest Errbit, and apply some fixes if they will be required. And I also think that I can continue supporting this gem. What do you think?

**Comment by stevecrozz** [comment]
I think that'd be fantastic. Thanks for jumping in!

**Comment by flexoid** [comment]
So, what should I do better with the repo?

**Comment by flexoid** [comment]
@stevecrozz So, we are using this plugin with latest errbit at least for the month, and it works well. Also, code seems fully compatible with latest version of [errbit_plugin](https://github.com/errbit/errbit_plugin).

**Comment by stevecrozz** [comment]
Very awesome. Sounds like everything is fine.
